# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-19 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_initial_tags_resource_types'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='attachments',
            field=models.ManyToManyField(to='resources.Attachment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
