# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-09 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='resources.Attachment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief tagline for display on project card in browse view', max_length=255),
        ),
    ]
