# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-21 14:54
from __future__ import unicode_literals

from django.db import migrations

def create_staff_rd_grant_type(apps, schema_editor):
    # create Staff R&D and postdoc grant types if they do not already exist
    GrantType = apps.get_model('projects', 'GrantType')
    GrantType.objects.get_or_create(grant_type='Staff R&D')
    GrantType.objects.get_or_create(grant_type='Postdoctoral Research Project')

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_make_grant_end_date_optional'),
    ]

    operations = [
        migrations.RunPython(create_staff_rd_grant_type,
                             reverse_code=migrations.RunPython.noop),
    ]
