# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-26 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_staff_rd_grant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='status_override',
            field=models.CharField(blank=True, choices=[('current', 'Show member as current'), (
                'past', 'Show member as alum')], default='', max_length=7, verbose_name='Status Override'),
        ),
    ]
