# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-08 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_membership_status_override'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grant',
            options={'ordering': ['start_date', 'project']},
        ),
        migrations.AlterField(
            model_name='membership',
            name='status_override',
            field=models.CharField(blank=True, choices=[('current', 'Current'), ('past', 'Alum')], default='', help_text='Show the member as current or as an alum regardless of             associated project grant dates. Only use when displaying current                 or past project members based on grant dates is incorrect.', max_length=7, verbose_name='Status Override'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, verbose_name='URL'),
        ),
    ]
