# Generated by Django 5.0.5 on 2024-05-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_alter_project_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="show_jumplinks",
            field=models.BooleanField(
                default=False,
                help_text="When this box is checked a summary of page contents shows at the top of the page. Not needed on short pages. Jumplinks are generated from all page components with heading 'Show in jumplinks' checked.",
            ),
        ),
    ]
