# Generated by Django 2.2.17 on 2020-11-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_slug_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='working_group',
            field=models.BooleanField(default=False, help_text='Project is a long-term collaborative group associated with the CDH.', verbose_name='Working Group'),
        ),
    ]
