# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-10 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_working_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
