# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-10 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_calculate_membership_dates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ('role__sort_order', 'person__last_name')},
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='user',
            new_name='person',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='grant',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='status_override',
        ),
        migrations.AlterField(
            model_name='membership',
            name='start_date',
            field=models.DateField(),
        ),
    ]
