# Generated by Django 5.0.5 on 2024-06-04 22:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cdhpages", "0045_alter_landingpage_options"),
        ("projects", "0011_alter_project_body"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProjectsLandingPage",
            new_name="ProjectsLandingPageArchived",
        ),
    ]
