# Generated by Django 5.0.5 on 2024-06-04 23:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0013_projectslandingpage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="short_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="image",
            new_name="hero_image",
        ),
        migrations.RemoveField(
            model_name="project",
            name="highlight",
        ),
        migrations.RemoveField(
            model_name="project",
            name="thumbnail",
        ),
    ]
