# Generated by Django 5.0.5 on 2024-06-04 23:57

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0014_rename_short_description_project_description_and_more"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Short introduction to the page, aim for max two clear sentences (max. 200 chars). \n        Used to orient the user and help them identify relevancy of the page to meet their needs. ",
                max_length=200,
                null=True,
                verbose_name="Page Summary",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional image to support intent of the page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
