# Generated by Django 2.2.17 on 2020-12-22 20:26

from django.db import migrations


def membership_user_to_person(apps, _schema_editor):
    Membership = apps.get_model("projects", "membership")

    # Associate membership to person directly
    for membership in Membership.objects.all():
        membership.person = membership.user.person
        membership.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_membership_person'),
    ]

    operations = [
        migrations.RunPython(membership_user_to_person,
                             reverse_code=migrations.RunPython.noop)
    ]
