# Generated by Django 5.0.5 on 2024-06-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_project_description_alter_project_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_website',
            field=models.URLField(blank=True, help_text='Project website URL.', null=True, verbose_name='Project Website'),
        ),
    ]
