# Generated by Django 2.2.17 on 2020-12-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_membership_user_to_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='user',
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(through='projects.Membership', to='people.Person'),
        ),
        # revert field to non-nullable after it is populated
        migrations.AlterField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to='people.Person'),
        ),
    ]
