# Generated by Django 2.2.17 on 2021-01-14 21:35

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('sites', '0002_alter_domain_unique'),
        ('people', '0022_allow_bio_h2'),
        ('resources', '0008_userresource_to_personresource'),
        ('projects', '0016_project_member_to_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='project',
            field=models.ForeignKey('projects.Project', null=True, on_delete=models.CASCADE)
        ),
        migrations.AlterField(
            model_name='membership',
            name='project',
            field=models.ForeignKey('projects.Project', null=True, on_delete=models.CASCADE)
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='project',
            field=models.ForeignKey('projects.Project', null=True, on_delete=models.CASCADE)
        ),
        migrations.RenameField(
            model_name='grant',
            old_name='project',
            new_name='old_project',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='project',
            new_name='old_project',
        ),
        migrations.RenameField(
            model_name='projectresource',
            old_name='project',
            new_name='old_project',
        ),
    ]
