# Generated by Django 2.2.17 on 2021-01-15 14:36

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_rename_projectresource_to_projectrelatedlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectrelatedlink',
            options={},
        ),
        migrations.RenameField(
            model_name='projectrelatedlink',
            old_name='resource_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='projectrelatedlink',
            name='project',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='projects.Project'),
        ),
    ]
