# Generated by Django 2.2.17 on 2021-01-14 21:35

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_inherit_from_relatedlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='project',
            field=models.ForeignKey('projects.Project', null=True, editable=False, on_delete=models.CASCADE)
        ),
        migrations.AlterField(
            model_name='membership',
            name='project',
            field=models.ForeignKey('projects.Project', null=True, editable=False, on_delete=models.CASCADE)
        ),
        migrations.AlterField(
            model_name='projectrelatedlink',
            name='project',
            field=models.ForeignKey('projects.Project', null=True, editable=False, on_delete=models.CASCADE)
        ),
        migrations.RenameField(
            model_name='grant',
            old_name='project',
            new_name='old_project',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='project',
            new_name='old_project',
        ),
        migrations.RenameField(
            model_name='projectrelatedlink',
            old_name='project',
            new_name='old_project',
        ),
    ]
