# Generated by Django 2.2.17 on 2021-01-14 21:35

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_project_page_wagtail'),
    ]

    # NOTE approach for migrating foreign keys to page models; where "new" model
    # extends wagtail Page and "old" model extends mezzanine Displayable:
    #
    # [see 0020_project_page_wagtail.py]
    # 1. create new model with name FooPage (extends wagtail Page)
    # 2. add FKs to new model called "foo_page" on all models with FKs to old model
    #
    # [in this migration]
    # 2. rename FKs to old model, adding "old_" prefix
    # 3. make FKs to old model nullable but not editable in admin
    # 4. rename FKs to new model, removing "_page" suffix
    #
    # [see 0022_rename_project.py]
    # 5. rename old model Foo to OldFoo
    # 6. rename new model FooPage to Foo
    #
    # [in exodus script]
    # 7. create a Foo for each OldFoo
    # 8. set the value of all FKs to OldFoo to the Foo created in step 7
    #
    # [after exodus is complete]
    # 9. remove all OldFoo FKs
    # 10. remove OldFoo model

    operations = [
        migrations.RenameField(
            model_name='grant',
            old_name='project',
            new_name='old_project',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='project',
            new_name='old_project',
        ),
        migrations.RenameField(
            model_name='projectrelatedlink',
            old_name='project',
            new_name='old_project',
        ),
        migrations.AlterField(
            model_name='grant',
            name='old_project',
            field=models.ForeignKey('projects.Project', null=True, editable=False, on_delete=models.SET_NULL)
        ),
        migrations.AlterField(
            model_name='membership',
            name='old_project',
            field=models.ForeignKey('projects.Project', null=True, editable=False, on_delete=models.SET_NULL)
        ),
        migrations.AlterField(
            model_name='projectrelatedlink',
            name='old_project',
            field=models.ForeignKey('projects.Project', null=True, editable=False, on_delete=models.SET_NULL)
        ),
        migrations.RenameField(
            model_name='grant',
            old_name='project_page',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='project_page',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projectrelatedlink',
            old_name='project_page',
            new_name='project',
        ),
        migrations.AlterModelOptions(
            name='grant',
            options={'ordering': ['start_date', 'project']},
        ),
    ]
