# Generated by Django 2.2.17 on 2021-01-14 21:35

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_project_page_wagtail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grant',
            old_name='project',
            new_name='old_project',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='project',
            new_name='old_project',
        ),
        migrations.RenameField(
            model_name='projectrelatedlink',
            old_name='project',
            new_name='old_project',
        ),
        migrations.AlterField(
            model_name='grant',
            name='old_project',
            field=models.ForeignKey('projects.Project', null=True, editable=False, on_delete=models.SET_NULL)
        ),
        migrations.AlterField(
            model_name='membership',
            name='old_project',
            field=models.ForeignKey('projects.Project', null=True, editable=False, on_delete=models.SET_NULL)
        ),
        migrations.AlterField(
            model_name='projectrelatedlink',
            name='old_project',
            field=models.ForeignKey('projects.Project', null=True, editable=False, on_delete=models.SET_NULL)
        ),
        migrations.RenameField(
            model_name='grant',
            old_name='project_page',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='project_page',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projectrelatedlink',
            old_name='project_page',
            new_name='project',
        ),
        migrations.AlterModelOptions(
            name='grant',
            options={'ordering': ['start_date', 'project']},
        ),
    ]
