# Generated by Django 2.2.17 on 2021-01-21 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_rename_project_fks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='project',
            new_name='oldproject'
        ),
        migrations.RenameModel(
            old_name='projectpage',
            new_name='project'
        ),
    ]
