# Generated by Django 2.2.17 on 2021-02-02 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdhpages', '0004_merge_migration'),
        ('projects', '0022_rename_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsLinkPage',
            fields=[
                ('linkpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                      parent_link=True, primary_key=True, serialize=False, to='cdhpages.LinkPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('cdhpages.linkpage',),
        ),
    ]
