# Generated by Django 2.2.19 on 2021-03-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_nullable_project_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='updated',
        ),
    ]
