# Generated by Django 5.0.5 on 2024-07-03 08:43

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0026_add_project_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="accordion",
            field=wagtail.fields.StreamField(
                [
                    (
                        "accordion",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "accordion_items",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "heading",
                                                    wagtail.blocks.ChoiceBlock(
                                                        choices=[
                                                            ("code", "Code"),
                                                            ("data", "Data"),
                                                            (
                                                                "documentation",
                                                                "Documentation",
                                                            ),
                                                            (
                                                                "related_courses_and_course_modules",
                                                                "Related Courses and Course Modules",
                                                            ),
                                                            (
                                                                "project_peer_review",
                                                                "Project Peer Review",
                                                            ),
                                                        ]
                                                    ),
                                                ),
                                                (
                                                    "body",
                                                    wagtail.blocks.RichTextBlock(
                                                        features=[
                                                            "bold",
                                                            "italic",
                                                            "link",
                                                            "ol",
                                                            "ul",
                                                            "document-link",
                                                            "h3",
                                                            "h4",
                                                        ]
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                )
                            ],
                            label="Project Accordion",
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
                verbose_name="Project Details",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Short introduction to the page, aim for max two clear sentences (max. 200 chars). \n        Used to orient the user and help them identify relevancy of the page to meet their needs. ",
                max_length=200,
                null=True,
                verbose_name="Page Summary",
            ),
        ),
        migrations.AlterField(
            model_name="projectslandingpage",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Short introduction to the page, aim for max two clear sentences (max. 200 chars). \n        Used to orient the user and help them identify relevancy of the page to meet their needs. ",
                max_length=200,
                null=True,
                verbose_name="Page Summary",
            ),
        ),
    ]
