# Generated by Django 5.0.5 on 2024-07-03 21:43

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0027_project_accordion_alter_project_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="accordion",
            field=wagtail.fields.StreamField(
                [
                    (
                        "accordion",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "accordion_items",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "heading",
                                                    wagtail.blocks.ChoiceBlock(
                                                        choices=[
                                                            ("code", "Code"),
                                                            ("data", "Data"),
                                                            (
                                                                "documentation",
                                                                "Documentation",
                                                            ),
                                                            ("analysis", "Analysis"),
                                                            (
                                                                "related_courses_and_course_modules",
                                                                "Related Courses and Course Modules",
                                                            ),
                                                            (
                                                                "project_peer_review",
                                                                "Project Peer Review",
                                                            ),
                                                            ("awards", "Awards"),
                                                        ]
                                                    ),
                                                ),
                                                (
                                                    "body",
                                                    wagtail.blocks.RichTextBlock(
                                                        features=[
                                                            "bold",
                                                            "italic",
                                                            "link",
                                                            "ol",
                                                            "ul",
                                                            "document-link",
                                                            "h3",
                                                            "h4",
                                                        ]
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                )
                            ],
                            label="Project Accordion",
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
                verbose_name="Project Details",
            ),
        ),
    ]
