# Generated by Django 2.2.18 on 2021-03-23 21:01

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('cdhpages', '0007_no_body_documents'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('projects', '0029_set_null_handlers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsLandingPage',
            fields=[
                ('landingpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cdhpages.LandingPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('cdhpages.landingpage',),
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ('role', 'person')},
        ),
        migrations.AlterField(
            model_name='grant',
            name='old_project',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.OldProject'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='project',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='old_project',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.OldProject'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='project',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='projectrelatedlink',
            name='old_project',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.OldProject'),
        ),
        migrations.AlterField(
            model_name='projectrelatedlink',
            name='project',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_links', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='projecttag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='projects.Project'),
        ),
        migrations.DeleteModel(
            name='ProjectsLinkPage',
        ),
    ]
