# Generated by Django 5.0.5 on 2024-07-10 02:09

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0030_alter_project_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="field",
        ),
        migrations.RemoveField(
            model_name="project",
            name="method",
        ),
        migrations.RemoveField(
            model_name="project",
            name="role",
        ),
        migrations.AddField(
            model_name="project",
            name="field",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, related_name="projects", to="projects.projectfield"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="method",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, related_name="projects", to="projects.projectmethod"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="role",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, related_name="projects", to="projects.projectrole"
            ),
        ),
    ]
