# Generated by Django 2.2.19 on 2021-04-02 17:59

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_projectlink_to_projectlanding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='old_project',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='old_project',
        ),
        migrations.RemoveField(
            model_name='projectrelatedlink',
            name='old_project',
        ),
        migrations.AlterField(
            model_name='grant',
            name='project',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='project',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='projectrelatedlink',
            name='project',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='projecttag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='projects.Project'),
        ),
        migrations.DeleteModel(
            name='oldproject',
        ),
    ]
