# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-19 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_attachment_pages'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='attachments',
            field=models.ManyToManyField(to='resources.Attachment'),
        ),
    ]
