# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-26 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_attachments_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature the post in the carousel on the homepage.', verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=mezzanine.core.fields.FileField(blank=True, help_text='Appears on the homepage carousel when post is featured.', max_length=255, null=True, verbose_name='Featured Image'),
        ),
    ]
