# Generated by Django 2.2.17 on 2020-12-22 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_slug_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='users',
            field=models.ManyToManyField(related_name='blogposts', to=settings.AUTH_USER_MODEL, verbose_name='Authors'),
        ),
    ]
