# Generated by Django 2.2.17 on 2021-03-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_wagtail_models'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='OldBlogPost',
        ),
        migrations.RenameModel(
            old_name='BlogPostPage',
            new_name='BlogPost',
        ),
    ]
