# Generated by Django 5.0.5 on 2024-05-30 01:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_alter_blogpost_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="show_jumplinks",
        ),
    ]
