# Generated by Django 2.2.17 on 2021-03-02 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0027_person_user'),
        ('blog', '0008_rename_wagtail_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='authors',
            field=models.ManyToManyField(related_name='posts', to='people.Person'),
        ),
        migrations.AlterField(
            model_name='oldblogpost',
            name='users',
            field=models.ManyToManyField(related_name='oldblogposts', to=settings.AUTH_USER_MODEL, verbose_name='Authors'),
        ),
    ]
