# Generated by Django 2.2.17 on 2021-03-08 20:24

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_orderable_authors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={},
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='content',
            new_name='body',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Optional. Brief description for preview display. Will also be used for search description (without tags), if one is not entered.'),
        ),
    ]
