# Generated by Django 2.2.19 on 2021-03-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogpost_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='updated',
        ),
    ]
