# Generated by Django 2.2.19 on 2021-03-17 19:51

from django.db import migrations
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_blogpost_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='attachments',
            field=wagtail.core.fields.StreamField([('document', wagtail.documents.blocks.DocumentChooserBlock()), ('link', wagtail.snippets.blocks.SnippetChooserBlock('cdhpages.ExternalAttachment'))], blank=True),
        ),
    ]
