# Generated by Django 5.0.5 on 2024-06-11 21:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_alter_blogpost_body"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="featured_image",
            new_name="image",
        ),
    ]
