# Generated by Django 5.0.5 on 2024-06-11 21:17

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0013_rename_featured_image_blogpost_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="alt_text",
            field=models.CharField(
                blank=True,
                help_text="Describe the image for screen readers",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="caption",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="A short caption for the image.", max_length=180
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="credit",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="A credit line or attribution for the image.",
                max_length=80,
            ),
        ),
    ]
