# Generated by Django 5.0.5 on 2024-06-11 21:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0014_blogpost_alt_text_blogpost_caption_blogpost_credit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Short introduction to the page, aim for max two clear sentences (max. 200 chars).",
                max_length=200,
                null=True,
                verbose_name="Blog description",
            ),
        ),
    ]
