# Generated by Django 5.0.5 on 2024-06-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0015_alter_blogpost_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="short_description",
            field=models.TextField(
                blank=True,
                help_text="A short description of the content for promotional or navigation purposes. Displayed on tiles, not on page itself.",
                max_length=130,
                verbose_name="Short description",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="short_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Displayed on tiles, breadcrumbs etc., not on page itself. ",
                max_length=80,
                verbose_name="Short title",
            ),
        ),
    ]
