# Generated by Django 2.2.19 on 2021-04-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0033_remove_m2m_blogpost_events'),
        ('blog', '0015_delete_oldblogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='people',
            field=models.ManyToManyField(related_name='posts', through='blog.Author', to='people.Person'),
        ),
    ]
