# Generated by Django 5.0.5 on 2024-06-11 21:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0016_blogpost_short_description_blogpost_short_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="article_date",
            field=models.DateTimeField(
                default=django.utils.timezone.localdate,
                help_text="Published date for blog post",
                verbose_name="Published date",
            ),
        ),
    ]
