language: python
python:
- '3.5'
addons:
  chrome: stable
  firefox: latest
cache:
  pip: true
  directories:
  - downloads
  - node_modules
install:
- pip install -r requirements/test.txt
- pip install codecov
- npm ci
- cp ci/testsettings.py cdhweb/local_settings.py
- python -c "import uuid; print('SECRET_KEY = \'%s\'' % uuid.uuid4())" >> cdhweb/local_settings.py
before_script:
- sudo chown root /opt/google/chrome/chrome-sandbox
- sudo chmod 4755 /opt/google/chrome/chrome-sandbox
- mysql -u root -e "create database cdhweb";  # load and run site for pa11y to check
- mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
- python manage.py migrate
- python manage.py loaddata pa11y_test_site
- python manage.py compress -f -v0 # compress static assets
- python manage.py runserver --insecure --nobanner &  # run in insecure mode for static assets
script:
- py.test --cov=cdhweb
- npm run pa11y
services:
- mysql
after_success:
- codecov
notifications:
  slack:
    secure: aj/+9gYRfdUMRpce4DjKgJ/zdGGzUI1TiaVN382+KtU8j6JyRR4PXsT2KqEt3qiLqoP3wbCRr37shv/HjDOYtWV8BdoKC8BvBLgrj60ifhubCFwGohvA9aqNj43wUDtQrFmjCVgUxhYzxWGkSx4OXEiANWO+72Ebid976HeLOHplfH7IDl6+SpOUyZbuL3+kLjswRxYnwNSuctORAo/evTOlqbQ46M6ok8ubJgp65He3zfizk7bds7CZT51j4YzSw/7jckZocXbrBIXO+VSO8kQXsjt+xjDTRnlCmO3mGjg+KFEsSG8gplPJWZlI8sNIeK9zcOTWMgKMLzgeQCVqEslCA7cb/GnMQRGhgd5OflDddh632SPkioYkGAtkc4IJVQjA9vkeRrwRDO38sBZSBNlAnUCD258YBP89/xKyTDGsEHAdo9MIaHQ32y+70oFkMwylvvC/x9oW+XHssaouPNeUjrahAYbJGgqMRVLBW4/27cdk61tJUX/2dkVYX0aC+DLhr+L8enkTNZlvRwGqTjtPkB3l6rnAO/bkmhf3eGkZDhv0jIx8qIG/x67HqkqzyUn/ozAvPeE2lMD5MEcTiUS7aVzFuJIepmgu6znzDiQROGh+gYwx0iuxRBWaWPQ47fudtOF+AsMrrBDLPyF9RmPchSQLg/C03Yi6CaZz/Qo=
