# Generated by Django 2.2.19 on 2021-05-03 16:47

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks
import wagtail.snippets.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0060_fix_workflow_unique_constraint"),
        ("wagtailimages", "0023_add_choose_permissions"),
        ("people", "0001_initial"),
        ("cdhpages", "__first__"),
        ("taggit", "0003_taggeditem_add_unique_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "body",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "paragraph",
                                wagtail.core.blocks.RichTextBlock(
                                    features=[
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "blockquote",
                                        "document",
                                        "superscript",
                                        "subscript",
                                        "strikethrough",
                                        "code",
                                    ]
                                ),
                            ),
                            (
                                "image",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(),
                                        ),
                                        (
                                            "alternative_text",
                                            wagtail.core.blocks.TextBlock(
                                                help_text="Alternative text for visually impaired users to\nbriefly communicate the intended message of the image in this context.",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "caption",
                                            wagtail.core.blocks.RichTextBlock(
                                                features=[
                                                    "bold",
                                                    "italic",
                                                    "link",
                                                    "superscript",
                                                ],
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "svg_image",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.documents.blocks.DocumentChooserBlock(),
                                        ),
                                        (
                                            "alternative_text",
                                            wagtail.core.blocks.TextBlock(
                                                help_text="Alternative text for visually impaired users to\nbriefly communicate the intended message of the image in this context.",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "caption",
                                            wagtail.core.blocks.RichTextBlock(
                                                features=[
                                                    "bold",
                                                    "italic",
                                                    "link",
                                                    "superscript",
                                                ],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "extended_description",
                                            wagtail.core.blocks.RichTextBlock(
                                                features=["p"],
                                                help_text="This text will only be read to     non-sighted users and should describe the major insights or     takeaways from the graphic. Multiple paragraphs are allowed.",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            ("embed", wagtail.embeds.blocks.EmbedBlock()),
                            (
                                "migrated",
                                wagtail.core.blocks.RichTextBlock(
                                    features=[
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "blockquote",
                                        "document",
                                        "superscript",
                                        "subscript",
                                        "strikethrough",
                                        "code",
                                        "image",
                                        "embed",
                                    ],
                                    icon="warning",
                                ),
                            ),
                        ],
                        blank=True,
                    ),
                ),
                (
                    "attachments",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "document",
                                wagtail.documents.blocks.DocumentChooserBlock(),
                            ),
                            (
                                "link",
                                wagtail.snippets.blocks.SnippetChooserBlock(
                                    "cdhpages.ExternalAttachment"
                                ),
                            ),
                        ],
                        blank=True,
                    ),
                ),
                ("sponsor", models.CharField(blank=True, max_length=80, null=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "attendance",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total number of people who attended the event. (Internal only, for reporting purposes.)",
                        null=True,
                    ),
                ),
                (
                    "join_url",
                    models.URLField(
                        blank=True,
                        help_text="Join URL for virtual events, e.g. Zoom meetings.",
                        null=True,
                        verbose_name="Join URL",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image for display on event detail page (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="EventsLinkPage",
            fields=[
                (
                    "linkpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cdhpages.LinkPage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cdhpages.linkpage",),
        ),
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the location", max_length=255),
                ),
                ("short_name", models.CharField(blank=True, max_length=80)),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Address of the location (will not display if same as name)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "is_virtual",
                    models.BooleanField(
                        default=False,
                        help_text="Virtual platforms, i.e. Zoom or Google Hangouts",
                        verbose_name="Virtual",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speakers",
                        to="events.Event",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="people.Person"
                    ),
                ),
            ],
            options={
                "ordering": ("person",),
            },
        ),
        migrations.CreateModel(
            name="EventTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="events.Event",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events_eventtag_items",
                        to="taggit.Tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.Location",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="people",
            field=models.ManyToManyField(
                related_name="events", through="events.Speaker", to="people.Person"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="events.EventTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="thumbnail",
            field=models.ForeignKey(
                blank=True,
                help_text="Image for display on event card (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.EventType",
            ),
        ),
    ]
