# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-09 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='resources.Attachment'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(help_text='Addres of the location (will not display if same as name)', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Name of the location', max_length=255),
        ),
    ]
