# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-16 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_attachments_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendance',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of people who attended the event. (Internal only, for reporting purposes.)', null=True),
        ),
    ]
