# Generated by Django 2.2.15 on 2020-09-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_location_ondelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.URLField(blank=True, help_text='URL for virtual events, e.g. Zoom meetings.', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_virtual',
            field=models.BooleanField(default=False, help_text='Virtual platforms, i.e. Zoom or Google Hangouts'),
        ),
    ]
