# Generated by Django 2.2.15 on 2020-09-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_virtual_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(help_text='Address of the location (will not display if same as name)', max_length=255, null=True, blank=True),
        ),
    ]
