# Generated by Django 2.2.17 on 2020-12-22 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_virtual_address_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(blank=True, help_text='Guest lecturer(s) or Workshop leader(s)', to=settings.AUTH_USER_MODEL),
        ),
    ]
