# Generated by Django 5.0.5 on 2024-05-30 01:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0009_alter_event_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="show_jumplinks",
        ),
    ]
