# Generated by Django 2.2.17 on 2021-02-17 17:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('resources', '0012_move_personresource_to_people_app'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0011_wagtail_event_models'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='OldEvent',
        ),
        migrations.RenameModel(
            old_name='EventPage',
            new_name='Event',
        ),
    ]
