# Generated by Django 2.2.17 on 2021-02-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_modeladmin_perms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-start_time',)},
        ),
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('name',)},
        ),
    ]
