# Generated by Django 2.2.17 on 2021-03-11 16:39

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0028_person_posts'),
        ('events', '0014_default_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='speakers',
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('event', modelcluster.fields.ParentalKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='events.Event')),
                ('person', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='people.Person')),
            ],
            options={
                'ordering': ('person__last_name', 'person__first_name')
            },
        ),
    ]
