# Generated by Django 2.2.19 on 2021-03-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_speakers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='updated',
        ),
    ]
