# Generated by Django 2.2.19 on 2021-03-31 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_no_body_documents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OldEvent',
        ),
    ]
