# Generated by Django 2.2.19 on 2021-04-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0033_remove_m2m_blogpost_events'),
        ('events', '0019_delete_oldevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='people',
            field=models.ManyToManyField(related_name='events', through='events.Speaker', to='people.Person'),
        ),
    ]
