# Generated by Django 5.0.5 on 2025-07-01 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0025_cdh97_index_preface"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="rsvp_text",
            field=models.CharField(
                blank=True,
                default="RSVP",
                help_text="Text for the RSVP button, this will default to RSVP if left blank",
                max_length=20,
                null=True,
                verbose_name="RSVP Text",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="rsvp_url",
            field=models.URLField(
                blank=True,
                help_text="RSVP URL for events",
                null=True,
                verbose_name="RSVP URL",
            ),
        ),
    ]
