# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-09 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_profile_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='resources.Attachment'),
        ),
    ]
