# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-21 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_attachments_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pu_status',
            field=models.CharField(blank=True, choices=[('fac', 'Faculty'), ('stf', 'Staff'), ('graduate', 'Graduate Student'), ('undergraduate', 'Undergraduate Student'), ('external', 'Not associated with Princeton')], default='', max_length=15, verbose_name='Princeton Status'),
        ),
    ]
