# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_exec_committee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, help_text='Academic Department at Princeton or other institution (optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='institution',
            field=models.CharField(blank=True, help_text='Institutional affiliation (for people not associated with Princeton)', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.CharField(blank=True, help_text='Professional title, e.g. Professor or Assistant Professor', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='CDH staff or Postdoctoral Fellow. If checked, person will be listed on the CDH staff page (except for postdocs) and will have a profile page on the site.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
    ]
