# Generated by Django 2.2.17 on 2020-12-22 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_profile_slug_not_null'),
        # ensure that all person proxies are removed before this migration runs
        ('projects', '0013_unproxy_user'),
        ('events', '0010_unproxy_user'),
        ('blog', '0006_unproxy_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-user__last_name']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
