# Generated by Django 2.2.17 on 2020-12-22 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailimages', '0022_uploadedimage'),
        ('people', '0009_remove_person_proxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cdh_staff', models.BooleanField('CDH Staff', default=False, help_text='CDH staff or Postdoctoral Fellow.')),
                ('job_title', models.CharField(blank=True, help_text='Professional title, e.g. Professor or Assistant Professor', max_length=255)),
                ('department', models.CharField(blank=True, help_text='Academic Department at Princeton or other institution (optional)', max_length=255)),
                ('institution', models.CharField(blank=True, help_text='Institutional affiliation (for people not associated with Princeton)', max_length=255)),
                ('pu_status', models.CharField(blank=True, choices=[('fac', 'Faculty'), ('stf', 'Staff'), ('graduate', 'Graduate Student'), ('undergraduate', 'Undergraduate Student'), ('external', 'Not associated with Princeton')], default='', max_length=15, verbose_name='Princeton Status')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('user', models.OneToOneField(blank=True, help_text='Corresponding user account for this person (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
