# Generated by Django 5.0.5 on 2024-05-30 01:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0009_alter_profile_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="show_jumplinks",
        ),
    ]
