# Generated by Django 5.0.5 on 2024-05-30 23:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cdhpages", "0041_contentpage_disable_sidebar"),
        ("people", "0010_remove_profile_show_jumplinks"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PeopleLandingPage",
            new_name="PeopleLandingPageArchived",
        ),
    ]
