# Generated by Django 2.2.17 on 2020-12-23 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_populate_nonproxy_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
    ]
