# Generated by Django 2.2.17 on 2020-12-23 14:55

from django.db import migrations, models


def position_user_to_person(apps, _schema_editor):
    Position = apps.get_model("people", "position")

    # Associate position to person directly
    for position in Position.objects.all():
        position.person = position.user.person
        position.save()


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_position_person'),
    ]

    operations = [
        migrations.RunPython(position_user_to_person,
                             reverse_code=migrations.RunPython.noop),
    ]
