# Generated by Django 2.2.17 on 2020-12-23 16:50

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_title_user_to_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='person',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='people.Person'),
        ),
    ]
