# Generated by Django 2.2.17 on 2020-12-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_person_cluster_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='office_location',
            field=models.CharField(blank=True, help_text='Office location (optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Office phone number (optional)', max_length=50),
        ),
    ]
