# Generated by Django 2.2.17 on 2020-12-23 18:23

from django.db import migrations


def profile_phone_office_to_person(apps, _schema_editor):
    """Transfer phone numbers and office locations from Profiles to People."""
    Profile = apps.get_model("people", "profile")

    # Get all the profiles and find their associated person via user,
    # copy phone number and office location onto the person
    for profile in Profile.objects.all():
        person = profile.user.person
        person.phone_number = profile.phone_number
        person.office_location = profile.office_location
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_person_phone_office'),
    ]

    operations = [
        migrations.RunPython(profile_phone_office_to_person,
                             reverse_code=migrations.RunPython.noop)
    ]
