# Generated by Django 2.2.17 on 2021-01-05 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0019_profilepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('last_name',), 'verbose_name_plural': 'people'},
        ),
    ]
