# Generated by Django 5.0.5 on 2024-06-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0020_remove_peoplelandingpage_attachments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplecategorypage',
            name='category',
            field=models.CharField(choices=[('staff', 'Staff'), ('past_staff', 'Past Staff'), ('students', 'Students'), ('alumni', 'Alumni'), ('affiliates', 'Affiliates'), ('past_affiliates', 'Past Affiliates'), ('executive_committee', 'Executive Committee'), ('sits_with_executive_committee', 'Sits with Executive Committee')]),
        ),
    ]
