# Generated by Django 2.2.17 on 2021-01-05 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdhpages', '0001_initial'),
        ('people', '0020_person_ordering_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleLandingPage',
            fields=[
                ('landingpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cdhpages.LandingPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('cdhpages.landingpage',),
        ),
    ]
