# Generated by Django 2.2.17 on 2021-01-15 15:48

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0022_personrelatedlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personrelatedlink',
            options={'ordering': ['sort_order']},
        ),
        migrations.RenameField(
            model_name='personrelatedlink',
            old_name='resource_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='personrelatedlink',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='personrelatedlink',
            name='person',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='people.Person'),
        )
    ]
