# Generated by Django 2.2.17 on 2021-01-15 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0022_allow_bio_h2'),
        ('people', '0023_inherit_from_relatedlink'),
    ]

    operations = [
    ]
