# Generated by Django 2.2.17 on 2021-01-22 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0024_merge_migrations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='oldprofile'
        ),
        migrations.RenameModel(
            old_name='profilepage',
            new_name='profile'
        ),
    ]
