# Generated by Django 2.2.17 on 2021-02-09 21:15

from django.contrib.auth.management import create_permissions
from django.db import migrations


def create_people_permissions(apps, schema_editor):
    """Set Wagtail user group permissions for non-Page People models.

    By default, Wagtail creates the Moderator and Editor user groups. Users who
    access the wagtail backend (/cms) must be in one of these groups.

    Models that inherit from Wagtail's `Page` will have permissions set up for
    these groups, but Django models that can be managed via Wagtail (through
    the use of `modeladmin`) will not have permissions set up and will not be
    visible in Wagtail unless permissions are manually added.

    For People, the relevant models are `Title` and `Person`. `Position` and
    `PersonRelatedLink` are editable by default as inlines on `Person`.
    """

    # ensure that permissions exist for all models in the module; in context of
    # tests they may not yet
    people_cfg =  apps.get_app_config("people")
    people_cfg.models_module = True
    create_permissions(people_cfg, apps=apps, verbosity=0)
    people_cfg.models_module = None

    # get groups and error if any aren't present - they should be since
    # wagtail's own migrations have already run
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    editors = Group.objects.get(name="Editors")
    moderators = Group.objects.get(name="Moderators")

    # get permissions to assign
    add_title = Permission.objects.get(codename="add_title")
    change_title = Permission.objects.get(codename="change_title")
    delete_title = Permission.objects.get(codename="delete_title")
    view_title = Permission.objects.get(codename="view_title")
    add_person = Permission.objects.get(codename="add_person")
    change_person = Permission.objects.get(codename="change_person")
    delete_person = Permission.objects.get(codename="delete_person")
    view_person = Permission.objects.get(codename="view_person")

    # give moderators all permissions on Title and Person
    moderators.permissions.add(
        add_title, change_title, delete_title, view_title,
        add_person, change_person, delete_person, view_person
    )

    # editors have all permissions on Person, but none for Title
    editors.permissions.add(
        add_person, change_person, delete_person, view_person
    )


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0025_rename_profile"),
    ]

    operations = [
        migrations.RunPython(create_people_permissions,
                             reverse_code=migrations.RunPython.noop)
    ]
