# Generated by Django 2.2.17 on 2021-03-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_speakers'),
        ('people', '0028_person_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='events',
            field=models.ManyToManyField(through='events.Speaker', to='events.Event'),
        ),
    ]
