# Generated by Django 2.2.19 on 2021-04-02 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0032_delete_oldprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='events',
        ),
        migrations.RemoveField(
            model_name='person',
            name='posts',
        ),
    ]
