# Generated by Django 2.2.17 on 2021-01-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdhpages', '0001_initial'),
        ('resources', '0009_move_resourcetype_to_pages_app')
    ]

    state_operations = [
        migrations.CreateModel(
            name='RelatedLinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
                'db_table': 'cdhpages_relatedlinktype'
            }
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
