# Generated by Django 2.2.17 on 2021-01-15 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdhpages', '0002_allow_body_h2'),
        ('cdhpages', '0002_linkpage_pageintro'),
    ]

    operations = [
    ]
