# Generated by Django 2.2.17 on 2021-01-15 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdhpages', '0003_merge_20210115_1637'),
        ('cdhpages', '0002_relatedlinktype'),
    ]

    operations = [
    ]
