# Generated by Django 2.2.17 on 2021-02-16 20:02

from django.contrib.auth.management import create_permissions
from django.db import migrations


def create_pages_permissions(apps, schema_editor):
    """Set Wagtail user group permissions for non-Page Pages models.

    By default, Wagtail creates the Moderator and Editor user groups. Users who
    access the wagtail backend (/cms) must be in one of these groups.

    Models that inherit from Wagtail's `Page` will have permissions set up for
    these groups, but Django models that can be managed via Wagtail (through
    the use of `modeladmin`) will not have permissions set up and will not be
    visible in Wagtail unless permissions are manually added.

    For Pages, the only relevant model is the `PageIntro` snippet. All users
    should be able to manage these snippets.
    """

    # ensure that permissions exist for all models in the module; in context of
    # tests they may not yet
    pages_cfg = apps.get_app_config("cdhpages")
    pages_cfg.models_module = True
    create_permissions(pages_cfg, apps=apps, verbosity=0)
    pages_cfg.models_module = None

    # get models and error if any aren't present - they should be since
    # wagtail's own migrations have already run
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    editors = Group.objects.get(name="Editors")
    moderators = Group.objects.get(name="Moderators")

    # get permissions to assign
    add_pageintro = Permission.objects.get(codename="add_pageintro")
    change_pageintro = Permission.objects.get(codename="change_pageintro")
    delete_pageintro = Permission.objects.get(codename="delete_pageintro")
    view_pageintro = Permission.objects.get(codename="view_pageintro")

    # give moderators and editors all permissions on PageIntro
    moderators.permissions.add(
        add_pageintro, change_pageintro, delete_pageintro, view_pageintro,
    )
    editors.permissions.add(
        add_pageintro, change_pageintro, delete_pageintro, view_pageintro,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('cdhpages', '0004_merge_migration'),
    ]

    operations = [
        migrations.RunPython(create_pages_permissions,
                             reverse_code=migrations.RunPython.noop)
    ]
