# Generated by Django 5.0.5 on 2024-05-08 23:23

import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdhpages', '0005_footer_level1menuitem_primarynavigation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryNavigationCTAButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=60, verbose_name='Menu title')),
                ('link', wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('external', wagtail.blocks.URLBlock())], use_json_field=True)),
                ('secondary_menu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='cta_button', to='cdhpages.secondarynavigation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
