# Generated by Django 5.0.5 on 2024-05-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdhpages', '0007_alter_contentpage_body_alter_homepage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level1menuitem',
            name='overview',
            field=models.TextField(blank=True, max_length=120, verbose_name='Section overview'),
        ),
        migrations.AlterField(
            model_name='level1menuitem',
            name='section_link_title',
            field=models.CharField(blank=True, max_length=60, verbose_name='Section link title'),
        ),
    ]
