# Generated by Django 5.0.5 on 2024-05-12 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cdhpages", "0008_alter_level1menuitem_overview_and_more"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="hero_image",
            field=models.ForeignKey(
                help_text="Image that conveys sense of site / brand",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="summary",
            field=models.TextField(
                help_text="Text that supports / qualifies the hero header and gives people a sense of who you are",
                max_length=150,
                null=True,
                verbose_name="Page Summary",
            ),
        ),
    ]
