# Generated by Django 5.0.5 on 2024-05-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cdhpages", "0009_alter_homepage_hero_image_alter_homepage_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="Text that supports / qualifies the hero header and gives people a sense of who you are",
                max_length=150,
                null=True,
                verbose_name="Page Summary",
            ),
        ),
    ]
