# Generated by Django 5.0.5 on 2024-05-14 01:52

import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cdhpages", "0017_alter_homepage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footercolumn",
            name="footer",
        ),
        migrations.CreateModel(
            name="ContactLinksItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", wagtail.fields.RichTextField()),
                (
                    "contact_link",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_links",
                        to="cdhpages.footer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhysicalAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", wagtail.fields.RichTextField()),
                (
                    "address",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="physical_address",
                        to="cdhpages.footer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsefulLinksItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("title", models.CharField(max_length=60, verbose_name="Menu title")),
                (
                    "link",
                    wagtail.fields.StreamField(
                        [
                            ("page", wagtail.blocks.PageChooserBlock()),
                            ("external", wagtail.blocks.URLBlock()),
                        ],
                        use_json_field=True,
                    ),
                ),
                (
                    "contact_link",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="useful_links",
                        to="cdhpages.footer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="ColumnItem",
        ),
        migrations.DeleteModel(
            name="FooterColumn",
        ),
    ]
