# Generated by Django 5.0.5 on 2024-05-16 03:43

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdhpages', '0020_socialmedialinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='address',
            field=wagtail.fields.RichTextField(default='', verbose_name='Physical Address'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PhysicalAddress',
        ),
    ]
