# Generated by Django 5.0.5 on 2024-05-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cdhpages", "0030_alter_socialmedialinks_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmedialinks",
            name="site",
            field=models.CharField(
                choices=[
                    ("bluesky", "Bluesky"),
                    ("twitter", "Twitter"),
                    ("linkedIn", "LinkedIn"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("github", "Github"),
                ]
            ),
        ),
    ]
