# Generated by Django 5.0.5 on 2024-05-30 01:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cdhpages", "0039_alter_landingpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentpage",
            name="attachments",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="attachments",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="show_jumplinks",
        ),
        migrations.RemoveField(
            model_name="landingpage",
            name="show_jumplinks",
        ),
    ]
