# Generated by Django 5.0.5 on 2024-05-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cdhpages", "0040_remove_contentpage_attachments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpage",
            name="disable_sidebar",
            field=models.BooleanField(
                default=False,
                help_text="Hide the sidebar menu showing siblings of this page.",
            ),
        ),
    ]
