# Generated by Django 5.0.5 on 2024-06-04 22:33

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdhpages', '0043_contentpage_attachments'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='header_image',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='tagline',
        ),
        migrations.AddField(
            model_name='landingpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Short introduction to the page, aim for max two clear sentences (max. 200 chars). \n        Used to orient the user and help them identify relevancy of the page to meet their needs. ', max_length=200, null=True, verbose_name='Page Summary'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='disable_sidebar',
            field=models.BooleanField(default=False, help_text='Hide the sidebar menu showing siblings of this page.'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Optional image to support intent of the page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
