# Generated by Django 5.0.5 on 2024-06-04 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdhpages', '0044_remove_landingpage_header_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landingpage',
            options={'verbose_name': 'Section Landing Page'},
        ),
    ]
