# Generated by Django 5.0.5 on 2024-07-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cdhpages", "0052_purplemode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purplemode",
            options={"verbose_name": "Purple Site Setting"},
        ),
        migrations.AlterField(
            model_name="purplemode",
            name="purple_mode",
            field=models.BooleanField(
                default=False,
                help_text="This will turn the site purple \n                                      by transforming all shades of cyan on the site into shades of purple",
            ),
        ),
    ]
