# Generated by Django 5.0.5 on 2024-07-05 01:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cdhpages", "0053_alter_purplemode_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="level1menuitem",
            name="section_link_title",
        ),
    ]
