# Generated by Django 5.0.5 on 2024-07-04 23:30

from django.db import migrations
from cdhweb.pages.models import ContentPage
from cdhweb.pages.blocks.cdh_hosted_video import HostedVideo

def migrate_embed_to_hosted_video_block(apps, schema_editor):
    BasePage = apps.get_model('cdhpages', 'ContentPage')

    for page in BasePage.objects.all():
        # Access the body StreamField
        body = page.body
        print(type(body))
        # Iterate through blocks in the body
        updated_body = []
        for block in body:
            # Find embed blocks
            if block.block_type == 'embed':
                print('embed')
                hosted_video_block = HostedVideo(  # Create a new HostedVideo block instance
                video_url=block.value,
                accessibility_description="Accessibility description goes here",
                )
                body.stream_block.get_prep_value(hosted_video_block)
                print(body.stream_block.get_prep_value(hosted_video_block))
                updated_body.append(('hosted_video', hosted_video_block))
        
        # updated_stream_value = page.body.stream_block.get_prep_value(updated_body)
        print(updated_body)
        # page.body = updated_stream_value
        # page.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cdhpages', '0054_alter_contentpage_body_alter_homepage_body_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_embed_to_hosted_video_block),
    ]
