# Generated by Django 5.0.5 on 2024-07-07 23:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cdhpages", "0055_alter_contentpage_attachments_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="linkpage",
            name="extra_classes",
        ),
        migrations.RemoveField(
            model_name="linkpage",
            name="link_page",
        ),
        migrations.RemoveField(
            model_name="linkpage",
            name="link_url",
        ),
        migrations.RemoveField(
            model_name="linkpage",
            name="url_append",
        ),
    ]
