# Generated by Django 5.0.5 on 2024-07-07 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdhpages', '0056_remove_linkpage_extra_classes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageIntro',
        ),
    ]
