# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-19 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('resources', '0002_initial_tags_resource_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='pages',
            field=models.ManyToManyField(related_name='attachments', to='pages.Page'),
        ),
    ]
