# Generated by Django 2.2.17 on 2020-12-23 15:37

from django.db import migrations


def resource_user_to_person(apps, _schema_editor):
    UserResource = apps.get_model("resources", "userresource")

    # Associate user resource to person directly
    for user_resource in UserResource.objects.all():
        user_resource.person = user_resource.user.person
        user_resource.save()


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_userresource_person'),
    ]

    operations = [
        migrations.RunPython(resource_user_to_person,
                             reverse_code=migrations.RunPython.noop),
    ]
