# Generated by Django 2.2.17 on 2020-12-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_userresource_user_to_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcetype',
            name='users',
        ),
        migrations.RemoveField(
            model_name='userresource',
            name='user',
        ),
        # revert field to non-nullable after it is populated
        migrations.AlterField(
            model_name='userresource',
            name='person',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to='people.Person'),
        ),
        # rename model to PersonResource
        migrations.RenameModel(
            old_name='userresource',
            new_name='personresource'
        )
    ]
