# Generated by Django 2.2.17 on 2021-01-11 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    # Before altering the model, ensure that all other app migrations have referenced it
    dependencies = [
        ('resources', '0008_userresource_to_personresource'),
        ('projects', '0016_project_member_to_person'),
        ('people', '0021_peoplelandingpage'),
        ('cdhpages', '0001_initial')
    ]

    operations = [
        # Move ResourceType from resources app to cdhpages app and rename to RelatedLinkType
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.AlterModelTable('ResourceType', 'cdhpages_relatedlinktype')],
            state_operations=[]
        )
    ]
