# Generated by Django 2.2.17 on 2021-01-11 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    # Deletion of the model needs to occur after all foreign keys are changed
    dependencies = [
        ('resources', '0010_update_personresource_field'),
        ('projects', '0017_update_to_relatedlinktype_field')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.DeleteModel('ResourceType')]
        )
    ]
