# Generated by Django 2.2.19 on 2021-03-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_move_personresource_to_people_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='pages',
            field=models.ManyToManyField(blank=True, related_name='old_attachments', to='pages.Page'),
        ),
    ]
