# Generated by Django 2.2.19 on 2021-03-31 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_delete_oldproject'),
        ('people', '0032_delete_oldprofile'),
        ('events', '0019_delete_oldevent'),
        ('blog', '0015_delete_oldblogpost'),
        ('pages', '0004_auto_20170411_0504'),
        ('resources', '0013_old_attachment_related_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='LandingPage',
        ),
    ]
